import './globals.css'
import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import Header from '@/components/header'
import { palette } from '@/constants/palette'
import { TheProvider } from '@/globalRedux/provider'

const msr = Montserrat({ subsets: ['latin'], weight: '300' })

export const metadata: Metadata = {
  title: 'Frontend portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body
        className={msr.className}
        style={{
          height: '100vh',
          backgroundColor: palette.main.blackBackground,
        }}
      >
        <TheProvider>
          <Header />
          {children}
        </TheProvider>
      </body>
    </html>
  )
}
